# Generated by Django 4.0.3 on 2022-04-12 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_type', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], max_length=100)),
                ('modified_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.ManyToManyField(choices=[(True, 'True'), (False, 'False')], related_name='is_admin', to=settings.AUTH_USER_MODEL)),
                ('is_member', models.ManyToManyField(choices=[(True, 'True'), (False, 'False')], related_name='is_member', to=settings.AUTH_USER_MODEL)),
                ('is_moderator', models.ManyToManyField(choices=[(True, 'True'), (False, 'False')], related_name='is_moderator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_msg', models.TextField(max_length=1000, unique=True)),
                ('approved', models.BooleanField()),
                ('modified_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
            ],
        ),
    ]
