# Generated by Django 4.0.3 on 2022-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_group_is_admin_alter_group_is_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
